from .defaults import INSTALLED_APPS, MIDDLEWARE_CLASSES

INSTALLED_APPS = list(INSTALLED_APPS)
INSTALLED_APPS.append('silk')

MIDDLEWARE_CLASSES = list(MIDDLEWARE_CLASSES)
MIDDLEWARE_CLASSES.insert(0, 'silk.middleware.SilkyMiddleware')
SILKY_PYTHON_PROFILER = True