version: '3'
services:

  nginx_nekmocom:
    restart: on-failure
    image: "nginx"
    volumes:
      - ./conf/nginx_nekmocom/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx_nekmocom/ssl:/etc/nginx/ssl:ro
      - ./data/nginx_nekmocom/log/:/var/log/nginx/
    volumes_from:
      - gunicorn_nekmocom
    networks:
      - nginx-proxy
      - default
    ports:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST: nekmo.com
    command: [ 'nginx-debug', '-g', 'daemon off;']

  nginx_nekmonet:
    restart: on-failure
    image: "nginx"
    volumes:
      - ./conf/nginx_nekmonet/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx_nekmonet/ssl:/etc/nginx/ssl:ro
      - ./data/nginx_nekmonet/log/:/var/log/nginx/
    volumes_from:
      - gunicorn_nekmonet
    networks:
      - nginx-proxy
      - default
    environment:
      VIRTUAL_HOST: nekmo.net
    ports:
      - "80"
      - "443"
    command: [ 'nginx-debug', '-g', 'daemon off;']

  gunicorn_nekmocom:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
      - ./data/gunicorn/logs:/var/log/gunicorn/
      - ./data/gunicorn/media:/media
      - ./data/gunicorn/uploads:/uploads
      - ./data/gunicorn/static:/static
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: nekmocom.settings.production_nekmocom

  gunicorn_nekmonet:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes_from:
      - gunicorn_nekmocom
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: nekmocom.settings.production_nekmonet
      BUILD_DJANGO: 0

    # Sólo disponible en XFS montado con la opción pquota
    # storage_opt:
    #   size: '10G'

  postgres:
    restart: on-failure
    image: postgres
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env

  memcached:
    restart: on-failure
    image: memcached
    env_file:
      - .env
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
